spring:
  application:
    name: linkedin-bot
  liquibase:
    change-log: 'classpath:db-migrations/changelog.xml'
    user: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?currentSchema=${DATABASE_SCHEMA}"
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    platform: POSTGRESQL
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      show_sql: true
    properties.hibernate.temp.use_jdbc_metadata_defaults: false


bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}
  admin:
    name: ${ADMIN_NICKNAME}
    chatId: ${ADMIN_CHATID}
  random:
    limit: ${BOT_RANDOM_LIMIT}

server:
  port: ${PORT:5000}